export const jobApplications = [
  {
    id: "app-123",
    companyName: "Amazing Inc.",
    companyWebsite: "https://amazinginc.com",
    jobTitle: "Software Engineer",
    position: "Full-time",
    stage: "Applied",
    applicationDate: new Date("2024-05-20").toISOString(),
    applicationResponseDate: new Date("2024-05-15").toISOString(),
    referalStatus: "No Referral",
    referalResponse: "",
  },
  {
    id: "app-456",
    companyName: "Technovation",
    companyWebsite: "https://technovation.io",
    jobTitle: "Data Analyst",
    position: "Contract",
    stage: "Interview Scheduled",
    applicationDate: new Date("2024-05-15").toISOString(),
    applicationResponseDate: new Date("2024-05-24").toISOString(),
    referalStatus: "Referral from John Doe",
    referalResponse: "Positive",
  },
  {
    id: "app-450",
    companyName: "Google",
    companyWebsite: "https://google.io",
    jobTitle: "Frontend Egineer",
    position: "Contract",
    stage: "Interview Scheduled",
    applicationDate: new Date("2024-05-15").toISOString(),
    applicationResponseDate: new Date("2024-05-24").toISOString(),
    referalStatus: "Referral from John Doe",
    referalResponse: "Positive",
  },
];
