export const jobApplications = [
  {
    id: "app-123",
    companyName: "Amazing Inc.",
    companyWebsite: "https://amazinginc.com",
    jobTitle: "Software Engineer",
    position: "Full-time",
    stage: "Applied",
    applicationDate: new Date("2024-05-20").toISOString(),
    applicationResponseDate: new Date("2024-05-15").toISOString(),
    referalStatus: "No Referral",
    referalResponse: "",
  },
  {
    id: "app-456",
    companyName: "Technovation",
    companyWebsite: "https://technovation.io",
    jobTitle: "Data Analyst",
    position: "Contract",
    stage: "Interview Scheduled",
    applicationDate: new Date("2024-05-15").toISOString(),
    applicationResponseDate: new Date("2024-05-24").toISOString(),
    referalStatus: "Referral from John Doe",
    referalResponse: "Positive",
  },
  {
    id: "app-450",
    companyName: "Google",
    companyWebsite: "https://google.io",
    jobTitle: "Frontend Egineer",
    position: "Contract",
    stage: "Interview Scheduled",
    applicationDate: new Date("2024-05-15").toISOString(),
    applicationResponseDate: new Date("2024-05-24").toISOString(),
    referalStatus: "Referral from John Doe",
    referalResponse: "Positive",
  },
  {
    id: "app-001",
    companyName: "DataTech Solutions",
    companyWebsite: "https://datatechsolutions.com",
    jobTitle: "Machine Learning Engineer",
    position: "Full-time",
    stage: "Phone Screening",
    applicationDate: "2024-05-10T00:00:00.000Z",
    applicationResponseDate: "2024-05-18T00:00:00.000Z",
    referalStatus: "Referral from Jane Smith",
    referalResponse: "Positive",
  },
  {
    id: "app-002",
    companyName: "InnovateX",
    companyWebsite: "https://innovatex.com",
    jobTitle: "Software Developer",
    position: "Internship",
    stage: "Technical Assessment",
    applicationDate: "2024-05-12T00:00:00.000Z",
    applicationResponseDate: "2024-05-20T00:00:00.000Z",
    referalStatus: "No referral",
    referalResponse: "",
  },
  {
    id: "app-003",
    companyName: "CodeCrafters Inc.",
    companyWebsite: "https://codecrafters.com",
    jobTitle: "Frontend Developer",
    position: "Contract",
    stage: "Technical Interview",
    applicationDate: "2024-05-14T00:00:00.000Z",
    applicationResponseDate: "2024-05-23T00:00:00.000Z",
    referalStatus: "Referral from Mark Johnson",
    referalResponse: "Positive",
  },
  {
    id: "app-004",
    companyName: "TechGenius Labs",
    companyWebsite: "https://techgeniuslabs.com",
    jobTitle: "Data Scientist",
    position: "Full-time",
    stage: "Final Interview",
    applicationDate: "2024-05-16T00:00:00.000Z",
    applicationResponseDate: "2024-05-25T00:00:00.000Z",
    referalStatus: "No referral",
    referalResponse: "",
  },
  {
    id: "app-005",
    companyName: "AI Innovations",
    companyWebsite: "https://aiinnovations.com",
    jobTitle: "AI Researcher",
    position: "Part-time",
    stage: "Offer Extended",
    applicationDate: "2024-05-18T00:00:00.000Z",
    applicationResponseDate: "2024-05-28T00:00:00.000Z",
    referalStatus: "No referral",
    referalResponse: "",
  },
  {
    id: "app-006",
    companyName: "Data Dynamics",
    companyWebsite: "https://datadynamics.io",
    jobTitle: "Data Analyst",
    position: "Full-time",
    stage: "Application Submitted",
    applicationDate: "2024-05-20T00:00:00.000Z",
    applicationResponseDate: "",
    referalStatus: "Referral from Sarah Lee",
    referalResponse: "Positive",
  },
  {
    id: "app-007",
    companyName: "TechSolutions Ltd.",
    companyWebsite: "https://techsolutionsltd.com",
    jobTitle: "Software Engineer",
    position: "Contract",
    stage: "Resume Review",
    applicationDate: "2024-05-22T00:00:00.000Z",
    applicationResponseDate: "",
    referalStatus: "No referral",
    referalResponse: "",
  },
  {
    id: "app-008",
    companyName: "DataGen Corp",
    companyWebsite: "https://datagen.com",
    jobTitle: "Data Engineer",
    position: "Full-time",
    stage: "Application Review",
    applicationDate: "2024-05-24T00:00:00.000Z",
    applicationResponseDate: "",
    referalStatus: "No referral",
    referalResponse: "",
  },
  {
    id: "app-009",
    companyName: "InnovaTech Solutions",
    companyWebsite: "https://innovatechsolutions.com",
    jobTitle: "AI Engineer",
    position: "Full-time",
    stage: "Phone Interview",
    applicationDate: "2024-05-26T00:00:00.000Z",
    applicationResponseDate: "",
    referalStatus: "No referral",
    referalResponse: "",
  },
  {
    id: "app-010",
    companyName: "DataMinds Co.",
    companyWebsite: "https://datamindsco.com",
    jobTitle: "Data Scientist",
    position: "Internship",
    stage: "Application Submitted",
    applicationDate: "2024-05-28T00:00:00.000Z",
    applicationResponseDate: "",
    referalStatus: "No referral",
    referalResponse: "",
  },
];
